import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GridBackground } from "@/components/ui/grid-background";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Attendance Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full h-screen antialiased text-white overflow-x-hidden overflow-y-auto bg-black`}
      >
        <GridBackground />
        {children}
        <Toaster richColors toastOptions={{
          // classNames: {
          //   success: 'bg-green-600 text-white border-green-700',
          //   error: 'bg-red-600 text-white border-red-700',
          //   warning: 'bg-yellow-500 text-black border-yellow-600',
          //   info: 'bg-blue-600 text-white border-blue-700',
          // }
        }} />
      </body>
    </html >
  );
}
